version: '3.5'
services:
    db:
        image: 'postgres'
        restart: 'always'
        env_file: /.env
        volumes:
            - data:/data/db
    backend-user:
        build:
            context: ./backend/user-service
        env_file: /.env
        image: duyph995/udagram-api-user:v1
    backend-feed:
        build:
            context: ./backend/feed-service
        env_file: /.env
        image: duyph995/udagram-api-feed:v1

    proxy:
        build:
            context: ./backend/nginx-proxy
        ports:
            - 8080:8080
        image: duyph995/reverseproxy:v1
        depends_on:
            - backend-user
            - backend-feed

    frontend:
        build:
            context: ./frontend
        image: duyph995/udagram-frontend:v1
        ports:
            - 8100:80
volumes:
    data:
