version: '3.5'
services:
    backend-user:
        build:
            context: ./backend/user-service
        image: duyph995/udagram-api-user:v1
    backend-feed:
        build:
            context: ./backend/feed-service
        image: duyph995/udagram-api-feed:v1
    proxy:
        build:
            context: ./backend/nginx-proxy
        image: duyph995/reverseproxy:v1
    frontend:
        build:
            context: ./frontend
        image: duyph995/udagram-frontend:v1
