apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed-api
  template:
    metadata:
      labels:
        app: feed-api
    spec:
      containers:
        - name: api-feed
          image: duyph995/udagram-api-feed:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: config-map
            - secretRef:
                name: secret-aws
            - secretRef:
                name: secret-postgres
