apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 2
  selector:
  matchLabels:
    app: frontend-app
  template:
    metadata:
    labels:
      app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: duyph995/udagram-frontend:latest
          ports:
            containerPort: 80
          restartPolicy: always
