apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-service
  name: frontend-service
spec:
  ports:
    - name: "frontend-port"
      port: 80
      targetPort: 80
  selector:
    app: frontend-app
